"""Verify historical palette fixture hashes without executing native code."""
import argparse
import hashlib
import json
from pathlib import Path

if __package__ in (None, ''):
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

FIXTURES = Path(__file__).resolve().parent / 'fixtures'


def verify(read_bytes, label, fixture_root=FIXTURES):
    """One hash-check owner for checked-in, generated and exported bytes."""
    fixtures = json.loads((fixture_root / 'provenance.json').read_text())['fixtures']
    if not fixtures:
        raise ValueError('Palette provenance has no fixture hashes')
    for name, expected in fixtures.items():
        if Path(name).name != name or name in ('.', '..'):
            raise ValueError(f'Invalid palette fixture filename: {name}')
        actual = hashlib.sha256(read_bytes(name)).hexdigest()
        if actual != expected:
            raise ValueError(f'{label}: {name} SHA-256 {actual}; expected {expected}')
    return fixtures


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--generated', type=Path, help='also verify an exported candidate directory')
    args = parser.parse_args(argv)
    fixtures = verify(lambda name: (FIXTURES / name).read_bytes(), 'checked-in fixtures')
    if args.generated is not None:
        verify(lambda name: (args.generated / name).read_bytes(), 'generated fixtures')
    print(f"{len(fixtures)} palette fixture hashes match" +
          (' checked-in and generated bytes' if args.generated is not None else ' checked-in bytes; no native replay'))


if __name__ == '__main__':
    main()
